version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/groovy-spock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java-junit4"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java-junit5"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java-junit5-no-plugin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/kotlin-junit5"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/kotlin-junit5-no-plugin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/kotlin-kotest"
    schedule:
      interval: "weekly"